{% set name = "broadbean" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfe3afea69529da246f7ca2803d0213c625f96b15a7ca4283b9c22f8fc5c655c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - versioningit
  run:
    - matplotlib-base
    - numpy >=1.12.1
    - python >={{ python_min }}
    - schema
    - versioningit

test:
  imports:
    - broadbean
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/QCoDeS/broadbean
  summary: Package for easily generating and manipulating signal pulses. Developed for use with qubits in the quantum computing labs of Copenhagen, Delft, and Sydney, but should be generally useable.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
    - jenshnielsen
    - astafan8
    - einsmein
    - picarro-yren
    - samantha-ho
    - trevormorgan
