{% set name = "broadbean" %}
{% set version = "0.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b20fd5532a99118304d7686d832c6910c8b2ce7725f8f2e4ea81e586f85fa54

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - versioningit
  run:
    - matplotlib-base
    - numpy >=1.12.1
    - python >=3.9
    - schema
    - versioningit

test:
  imports:
    - broadbean
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/QCoDeS/broadbean
  summary: Package for easily generating and manipulating signal pulses. Developed for use with qubits in the quantum computing labs of Copenhagen, Delft, and Sydney, but should be generally useable.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
    - jenshnielsen
