{% set name = "broadbean" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7be2c07265b14fe4a4696b53a0f820fb1dd046ee5f0929bec3874b09cc99af0f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base
    - numpy >=1.12.1
    - python >=3.7
    - schema

test:
  imports:
    - broadbean
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/QCoDeS/broadbean
  summary: Package for easily generating and manipulating signal pulses. Developed for use with qubits in the quantum computing labs of Copenhagen, Delft, and Sydney, but should be generally useable.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
    - jenshnielsen
